---
apiVersion: v2
description: A common powered chart template. Based on common library chart by bjw-s, with Database dependencies
name: app-template-extra
version: 0.2.0
maintainers:
  - name: lkmgr
    email: lkmgr@users.noreply.github.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.1.0
  - name: postgresql
    version: 11.8.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 11.3.0
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: influxdb
    version: 5.4.6
    repository: https://charts.bitnami.com/bitnami
    condition: influxdb.enabled
  - name: redis
    version: 16.13.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
