---
apiVersion: v2
description: A common powered chart template. Based on common library chart by bjw-s, with Database dependencies
name: app-template-extra
version: 2.0.0
maintainers:
  - name: lkmgr
    email: lkmgr@users.noreply.github.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
  - name: postgresql
    version: 12.6.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mariadb
    version: 11.5.7
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: influxdb
    version: 5.7.2
    repository: https://charts.bitnami.com/bitnami
    condition: influxdb.enabled
  - name: redis
    version: 17.11.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
