---
apiVersion: v2
description: A common powered chart template. Based on common library chart by bjw-s, with Bitnami PostgreSQL
name: app-template-postgres
version: 2.1.0
maintainers:
  - name: lkmgr
    email: lkmgr@users.noreply.github.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 2.6.0
  - name: postgresql
    version: 12.6.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
