---
apiVersion: v2
description: A common powered chart template. Based on common library chart by bjw-s, with Bitnami PostgreSQL
name: app-template-postgres
version: 0.3.1
maintainers:
  - name: lkmgr
    email: lkmgr@users.noreply.github.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 0.2.2
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
