---
{{- include "bjw-s.common.loader.init" . }}

{{- define "app-template-postgres.hardcodedValues" -}}

# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{ end }}

{{- end -}}
{{- $_ := mergeOverwrite .Values (include "app-template-postgres.hardcodedValues" . | fromYaml) -}}

{{ include "bjw-s.common.loader.generate" . }}
